apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosial-media-deployment
  labels:
    label-key1: label-value1
  annotations:
    annotation-key1: annotation-value1
spec:
  replicas: 3
  selector:
    matchLabels:
      label-key1: label-value1
  template:
    metadata:
      name: sosial-media-deployment
      labels:
        label-key1: label-value1
    spec:
      containers:
      - name: sosial-media
        image: dylanjuan/sosial-media
        ports:
        - containerPort: 80
