apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed-deployment
  labels:
    app: sosial-media
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sosial-media
  template:
    metadata:
      labels:
        app: sosial-media
    spec:
      containers:
      - name: sosial-media
        image: registry.hub.docker.com/dylanjuan/sosial-media
        ports:
        - containerPort: 80

